language: node_js
cache:
  directories:
    - ~/.npm
    - .nyc_output
node_js:
  - "12.7.0"
notifications:
  email: false
stages:
  - lint
  - test
  - coverage
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: lint
      name: eslint
      script: npx eslint .
    - stage: lint
      name: commitlint
      install:
        - npm i && npm i -g @commitlint/travis-cli
      script: commitlint-travis
    - stage: test
      node_js:
        - "12.7.0"
        - "10.24.1"
      script: npm t
    - stage: deploy
      script: npx semantic-release
